feat: (OPI CNI) This is the initial implementation of OPI CNI
opiproject/opi-cni pull request #7
Opened 2023-12-04 10:07 UTC by mardim91

Initial implementation of OPI CNI. Currently only Intel Mt.Evans IPUs are supported by this CNI. Target is to support more IPUs/DPUs in the future.  It has an integration with the [EVPN GW API](https://github.com/opiproject/opi-api/tree/main/network/evpn-gw) .

2023-12-14 16:17 UTC, nupurjai reviewed
Is this based on multus and secondary interface?

2023-12-14 17:06 UTC, mardim91 commented
> Is this based on multus and secondary interface?

Yes it is

2023-12-19 16:49 UTC, glimchb requested changes
in review

2023-12-19 16:49 UTC, glimchb commented on Dockerfile
> -# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
you should not remove copyright

2023-12-19 16:57 UTC, mardim91 commented
@glimchb In the last tsc meeting we have decided this is not the right repo to put the cni. Also the name is a bit confusing because this cni integrates directly with evpn gw api which is a use case API. So we have decided to name it differently and use the OPI-PoC repo for now. So no need to review this PR. I will close it.

2023-12-19 16:57 UTC, closed without merging

2023-12-19 16:59 UTC, glimchb commented
> @glimchb In the last tsc meeting we have decided this is not the right repo to put the cni. Also the name is a bit confusing because this cni integrates directly with evpn gw api which is a use case API. So we have decided to name it differently and use the OPI-PoC repo for now. So no need to review this PR. I will close it.

we can change the name, but still need new repo for it